name: Shopware Plugin Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            shopware-version:
                - 'v6.5.7.2'
                - 'v6.4.20.2'                  
    steps:
    - name: Setup Shopware
      uses: FriendsOfShopware/setup-shopware@v1
      with:
        shopware-version: v6.5.3.2
        php-version: 8.1
    - name: Setup Shopware Database
      run: composer setup
    - uses: actions/checkout@v3
      with:
          path: custom/plugins/iMidiPasswordSite
    - name: Install and activate plugin
      run: bin/console plugin:refresh && bin/console plugin:install -a iMidiPasswordSite
