name: Shopware Plugin Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          include:
            - shopware-version: 'v6.5.8.7'
              php-version: '8.1'
              node-version: '18'
            - shopware-version: 'v6.6.0.0-rc5'
              php-version: '8.2'            
              node-version: '20'
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Shopware
      uses: FriendsOfShopware/setup-shopware@v1
      with:
        php-version: ${{ matrix.php-version }}
        shopware-version: ${{ matrix.shopware-version }}
    - name: Setup Shopware Database
      run: composer setup
    - uses: actions/checkout@v3
      with:
          path: custom/plugins/ImiDiPasswordProtectedPages
    - name: Install and activate plugin
      run: export APP_SECRET=1 && bin/console plugin:refresh && bin/console plugin:install -a ImiDiPasswordProtectedPages
    - name: Run Tests
      run: |
          cd custom/plugins/ImiDiPasswordProtectedPages/
          TEST_TOKEN=none php -d pcov.enabled=1 ../../../vendor/bin/phpunit  tests/ --configuration=../../../phpunit.xml.dist --coverage-clover clover.xml

