name: Shopware Plugin Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            shopware-version:
                - 'v6.5.7.3'
    steps:
    - name: Setup Shopware
      uses: FriendsOfShopware/setup-shopware@v1
      with:
        php-version: 8.1
        shopware-version: ${{ matrix.shopware-version }}        
    - name: Setup Shopware Database
      run: echo 'APP_SECRET="def00000d0c06185824538c33f492f4639911a3e490157323013bc79fead08bbcab30e84508e5c741e1a636be478c92c6098510f981a87933a39ab5743362da0b2a4163a"' >> .env.local && composer setup
    - uses: actions/checkout@v3
      with:
          path: custom/plugins/ImiDiPasswordSite
    - name: Install and activate plugin
      run: bin/console plugin:refresh && bin/console plugin:install -a ImiDiPasswordSite
